name: velocityper

services:
  api:
    build: ./api
    depends_on:
      - db
      - redis
    networks:
      - default-bridge
    ports:
      - "6543:6543"

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - default-bridge

  #  db:
  #    image: postgres:17-alpine
  #    env_file: "compose.env"
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - postgres-data:/var/lib/postgresql/data
  #    healthcheck:
  #      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5
  #    networks:
  #      - default-bridge

  redis:
    image: redis:alpine
    env_file: "compose.env"
    ports:
      - "6379:6379"
    networks:
      - default-bridge

volumes:
  #postgres-data:

networks:
  default-bridge:
