name: velocityper

services:
  api:
    build: ./api
    env_file: "compose.env"
    depends_on:
      - redis
    ports:
      - "6543:6543"
    networks:
      - default-bridge

  web:
    build:
      context: ./web
    # have to supply a .env.production from web as nextjs detects args during buildtime not runtime, cannot provide compose.env here
    # read more: https://github.com/vercel/next.js/discussions/14030
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
       - default-bridge

  # Db exists in AWS RDS cluster
  #  db:
  #    image: postgres:17-alpine
  #    env_file: "compose.env"
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - postgres-data:/var/lib/postgresql/data
  #    healthcheck:
  #      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5
  #    networks:
  #      - default-bridge

  redis:
    image: redis:alpine
    env_file: "compose.env"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6380:6379"
    networks:
      - default-bridge

networks:
  default-bridge:
#volumes:
  #postgres-data:

