name: velocityper

services:
  api:
    build: ./api
    env_file: "compose.env"
    depends_on:
      - redis
    ports:
      - "6543:6543"
    networks:
      - default-bridge

  web:
    build:
      context: ./web
    # have to supply a .env.production from web as nextjs detects args during buildtime not runtime, cannot provide compose.env here
    # read more: https://github.com/vercel/next.js/discussions/14030
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
       - default-bridge


  # redis configuration loaded from mounted volume: redis_volume/redis.conf
  redis:
    image: redis:alpine
    command: redis-server  /usr/local/etc/redis/redis.conf
    volumes:
        - ./redis_volume:/usr/local/etc/redis
    ports:
      - "6380:6379"
    networks:
      - default-bridge

networks:
  default-bridge:

